name: Performance

on:
  workflow_dispatch:
  pull_request: 
    branches: 
      - "NidhiYadav726-patch-1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: perfaction for jmeter
        
        uses: QAInsights/PerfAction@2.0
        with:
          test-plan-path: './performance.jmx'

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
           name: jmeter-results
           path: result.jtl
