name: Performance
on:
  - pull_request
  - push
  - workflow_dispatch
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Artifacts Directory
        run: mkdir -p artifacts
      - name: JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
           test-plan-path: performance.jmx
           args: ""
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: artifacts/result.jtl
          if-no-files-found: error
