name: Performance

on:
  workflow_dispatch:
  pull_request: 
   branches: ["NidhiYadav726-patch-1"]
   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run JMeter Test
      
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ${{ github.event.inputs.test-file-path }}

      - name: Upload JMeter Results
        if: always() && steps.run-jmeter-test.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
