name: Performance

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run JMeter Test
        if: ${{ github.event.pull_request.base.ref != 'main' }}
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ${{ github.workspace }}/${{ github.event.pull_request.head.ref }}/performance.jmx

      - name: Upload JMeter Results
        if: always() && steps.run-jmeter-test.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
